### ISSUE TITLE
money transaction

### ISSUE THREAD

**Issue by Jon1111jo** [alephium/alephium-wallet#125]
02/08/2022 at 12:40 made a transfer of funds to the wallet 18PXTAkd6TQtV7X4cg2FEeLaUgyjoYG8tLUf44taGKeZb but the funds were not received. Solve the problem.

**Comment by Jon1111jo** [comment]
1. 1GZ7Z9eHp7w4zooAgXpHmgGemmGqT9s246LsbMaBnCKLK

![image](https://user-images.githubusercontent.com/99485222/153600192-cef1c9c2-d484-4d4a-9759-becb3689e756.png)

**Comment by Sakrecoer** [comment]
You sent the fund to 18PXTAkd6TQtV7X4cg2FEeLaUgyjoYG8tLUf44taGKeZB
instead of the one you mentioned [here](https://github.com/alephium/alephium-wallet/issues/125#issue-1132577825) which is: 18PXTAkd6TQtV7X4cg2FEeLaUgyjoYG8tLUf44taGKeZb

They look similar but the last letter is "b" in one and "B" in the other. It's case sensitive.

https://explorer.alephium.org/#/addresses/18PXTAkd6TQtV7X4cg2FEeLaUgyjoYG8tLUf44taGKeZB

https://explorer.alephium.org/#/addresses/18PXTAkd6TQtV7X4cg2FEeLaUgyjoYG8tLUf44taGKeZb

**Comment by nop33** [comment]
It seems that you sent `50.01` ALPH to the address:
- [`18PXTAkd6TQtV7X4cg2FEeLaUgyjoYG8tLUf44taGKeZB`](https://explorer.alephium.org/#/addresses/18PXTAkd6TQtV7X4cg2FEeLaUgyjoYG8tLUf44taGKeZB), and not to address:
- `18PXTAkd6TQtV7X4cg2FEeLaUgyjoYG8tLUf44taGKeZb` (notice the last character, it's lower case instead of upper case). The addresses are case-sensitive.

Here is the transaction: https://explorer.alephium.org/#/transactions/760c635560c21400c98cf189940dcff1069dc87541175bec397b7ba809462f21

**Comment by nop33** [comment]
The only way to retrieve the funds from the address 18PXTAkd6TQtV7X4cg2FEeLaUgyjoYG8tLUf44taGKeZB is to have the private key (or mnemonic phrase) of the wallet that generated this address.

Closing issue.
